In [5]:
import pandas as pd
from huggingface_hub import hf_hub_download
import duckdb

In [3]:
file_path = hf_hub_download(
    repo_id="rissin/nse-options-intraday",
    filename="upstox_intraday/NIFTY/NIFTY_2026.parquet",
    repo_type="dataset"
)

df = pd.read_parquet(file_path)

c:\GIT\.venv\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\akhil\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

upstox_intraday/NIFTY/NIFTY_2026.parquet: reconstructing file:   0%|          |  0.00B /  395MB

upstox_intraday/NIFTY/NIFTY_2026.parquet: downloading bytes:           |  0.00B

c:\GIT\.venv\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\akhil\.cache\huggingface\hub\datasets--rissin--nse-options-intraday. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [4]:
df.head()

,date,timestamp,underlying,expiry,strike,option_type,exercise_style,open,high,low,close,volume,oi,settle_price,source,granularity
0,2026-03-30,2026-03-30 15:29:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,532.00,532.00,531.25,531.25,260,17030,None,upstox_expired,1min
1,2026-03-30,2026-03-30 15:28:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,531.45,531.45,531.45,531.45,65,17030,None,upstox_expired,1min
2,2026-03-30,2026-03-30 15:27:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,531.75,531.75,531.75,531.75,0,17485,None,upstox_expired,1min
3,2026-03-30,2026-03-30 15:26:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,531.75,531.75,531.75,531.75,0,17485,None,upstox_expired,1min
4,2026-03-30,2026-03-30 15:25:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,530.35,531.75,530.15,531.75,780,17485,None,upstox_expired,1min

In [6]:
query = """
SELECT *
FROM read_parquet(?)
LIMIT 10
"""

chk_df1 = duckdb.execute(query, [file_path]).df()

chk_df1

,date,timestamp,underlying,expiry,strike,option_type,exercise_style,open,high,low,close,volume,oi,settle_price,source,granularity
0,2026-03-30,2026-03-30 15:29:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,532.00,532.00,531.25,531.25,260,17030,<NA>,upstox_expired,1min
1,2026-03-30,2026-03-30 15:28:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,531.45,531.45,531.45,531.45,65,17030,<NA>,upstox_expired,1min
2,2026-03-30,2026-03-30 15:27:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,531.75,531.75,531.75,531.75,0,17485,<NA>,upstox_expired,1min
3,2026-03-30,2026-03-30 15:26:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,531.75,531.75,531.75,531.75,0,17485,<NA>,upstox_expired,1min
4,2026-03-30,2026-03-30 15:25:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,530.35,531.75,530.15,531.75,780,17485,<NA>,upstox_expired,1min
5,2026-03-30,2026-03-30 15:24:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,533.45,533.45,533.00,533.00,585,17485,<NA>,upstox_expired,1min
6,2026-03-30,2026-03-30 15:23:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,533.80,534.45,533.80,534.45,130,17940,<NA>,upstox_expired,1min
7,2026-03-30,2026-03-30 15:22:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,529.20,532.15,529.20,532.15,585,17940,<NA>,upstox_expired,1min
8,2026-03-30,2026-03-30 15:21:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,529.55,530.00,529.55,530.00,195,17940,<NA>,upstox_expired,1min
9,2026-03-30,2026-03-30 15:20:00+05:30,NIFTY,2026-03-30,21800.0,CE,european,528.40,528.40,528.35,528.35,260,18200,<NA>,upstox_expired,1min

In [7]:
print("shape", df.shape)
print("cols: ", df.columns)
print(df.head())

shape (40177780, 16)
cols:  Index(['date', 'timestamp', 'underlying', 'expiry', 'strike', 'option_type',
       'exercise_style', 'open', 'high', 'low', 'close', 'volume', 'oi',
       'settle_price', 'source', 'granularity'],
      dtype='object')
         date                 timestamp underlying      expiry   strike  \
0  2026-03-30 2026-03-30 15:29:00+05:30      NIFTY  2026-03-30  21800.0
1  2026-03-30 2026-03-30 15:28:00+05:30      NIFTY  2026-03-30  21800.0
2  2026-03-30 2026-03-30 15:27:00+05:30      NIFTY  2026-03-30  21800.0
3  2026-03-30 2026-03-30 15:26:00+05:30      NIFTY  2026-03-30  21800.0
4  2026-03-30 2026-03-30 15:25:00+05:30      NIFTY  2026-03-30  21800.0

  option_type exercise_style    open    high     low   close  volume     oi  \
0          CE       european  532.00  532.00  531.25  531.25     260  17030
1          CE       european  531.45  531.45  531.45  531.45      65  17030
2          CE       european  531.75  531.75  531.75  531.75       0  17485
3          CE       european  531.75  531.75  531.75  531.75       0  17485
4          CE       european  530.35  531.75  530.15  531.75     780  17485

  settle_price          source granularity
0         None  upstox_expired        1min
1         None  upstox_expired        1min
2         None  upstox_expired        1min
3         None  upstox_expired        1min
4         None  upstox_expired        1min

In [8]:
print("Date range:")
print(df["date"].min(), "to", df["date"].max())

Date range:
2026-01-01 to 2026-07-21

In [9]:
print("Number of expiries:", df["expiry"].nunique())

print(
    df["expiry"]
    .drop_duplicates()
    .sort_values()
    .head(20)
)

Number of expiries: 29
355009    2026-01-06
383203    2026-01-13
239305    2026-01-20
76552     2026-01-27
154615    2026-02-03
131515    2026-02-10
386576    2026-02-17
225095    2026-02-24
131297    2026-03-02
143321    2026-03-10
210888    2026-03-17
315805    2026-03-24
0         2026-03-30
17894     2026-04-07
432846    2026-04-13
3274      2026-04-21
82926     2026-04-28
318381    2026-05-05
149603    2026-05-12
440977    2026-05-19
Name: expiry, dtype: object

In [10]:
print(df["option_type"].value_counts())

option_type
CE    20126296
PE    20051484
Name: count, dtype: int64

### NSE Daily close of NIFTY index

In [11]:
import requests
import pandas as pd
from io import StringIO

In [12]:
url = "https://www.nseindia.com/api/historicalOR/indicesHistory"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "application/json",
    "Referer": "https://www.nseindia.com/reports-indices-historical-index-data",
}

params = {
    "indexType": "NIFTY 50",
    "from": "01-01-2026",
    "to": "31-12-2026"
}

session = requests.Session()
session.headers.update(headers)

# Establish NSE session first
session.get("https://www.nseindia.com", timeout=20)

response = session.get(
    url,
    params=params,
    timeout=30
)

response.raise_for_status()

data = response.json()

data.keys()

dict_keys(['data'])

In [14]:
df = pd.DataFrame(data["data"])

In [19]:
print(data["data"][0])
print(data["data"][-1])

{'EOD_INDEX_NAME': 'NIFTY 50', 'EOD_OPEN_INDEX_VAL': 24385.2, 'EOD_HIGH_INDEX_VAL': 24400.95, 'EOD_CLOSE_INDEX_VAL': 24196.75, 'EOD_LOW_INDEX_VAL': 24102.8, 'HIT_TURN_OVER': 44634.35, 'HIT_TRADED_QTY': 508017772, 'EOD_TIMESTAMP': '16-APR-2026', 'HI_TIMESTAMP': '2026-04-15T18:30:00.000Z'}
{'EOD_INDEX_NAME': 'NIFTY 50', 'EOD_OPEN_INDEX_VAL': 26173.3, 'EOD_HIGH_INDEX_VAL': 26197.55, 'EOD_CLOSE_INDEX_VAL': 26146.55, 'EOD_LOW_INDEX_VAL': 26113.4, 'HIT_TURN_OVER': 23454.66, 'HIT_TRADED_QTY': 425631910, 'EOD_TIMESTAMP': '01-JAN-2026', 'HI_TIMESTAMP': '2025-12-31T18:30:00.000Z'}

In [27]:
# params = {
#     "indexType": "NIFTY 50",
#     "from": "01-01-2026",
#     "to": "31-01-2026"
# }

# params = {
#     "indexType": "NIFTY 50",
#     "from": "01-01-2026",
#     "to": "31-03-2026"
# }

params1 = {
    "indexType": "NIFTY 50",
    "from": "01-01-2026",
    "to": "31-03-2026"
}

response1 = session.get(
    url,
    params=params1,
    timeout=30
)

data1 = response1.json()["data"]

params2 = {
    "indexType": "NIFTY 50",
    "from": "01-04-2026",
    "to": "30-06-2026"
}

response2 = session.get(
    url,
    params=params2,
    timeout=30
)

data2 = response2.json()["data"]

print(len(data1))
print(data1[0]["EOD_TIMESTAMP"])
print(data1[-1]["EOD_TIMESTAMP"])

print(len(data2))
print(data2[0]["EOD_TIMESTAMP"])
print(data2[-1]["EOD_TIMESTAMP"])

60
30-MAR-2026
01-JAN-2026
60
30-JUN-2026
01-APR-2026

In [28]:
nifty1 = pd.DataFrame([
    {
        "date": x["EOD_TIMESTAMP"],
        "close": x["EOD_CLOSE_INDEX_VAL"]
    }
    for x in data1
])

nifty1["date"] = pd.to_datetime(nifty1["date"],format="%d-%b-%Y")

nifty2 = pd.DataFrame([
    {
        "date": x["EOD_TIMESTAMP"],
        "close": x["EOD_CLOSE_INDEX_VAL"]
    }
    for x in data2
])

nifty2["date"] = pd.to_datetime(nifty2["date"],format="%d-%b-%Y")

nifty1 = nifty1.sort_values("date").reset_index(drop=True)
nifty2 = nifty2.sort_values("date").reset_index(drop=True)
nifty = pd.concat([nifty1, nifty2], axis = 0)

In [30]:
nifty.to_csv('nift_close.csv', index= False)